### PR TITLE
V3.0.0

### PR DESCRIPTION
**Pull request by prc5**
- Removed render props performance issues. I've removed state from render props, now if we want to listen to it's changes we need to use useTransformEffect hook
- Created helper hooks for handling controls, transform state and context without performance issues with rerendering
- Added KeepScale, MiniMap components
- Added documentation about new hooks
- New readme
- Semantic release

### CODE REVIEW

**Comment by cojoclaudiu** [comment]
The V3 will be done today?

**Comment by prc5** [comment]
> The V3 will be done today?

Hopefully! It looks like it needs few checks around automation and we are ready! ⚡︎

The best thing is the semantic release which automate a lot of manual work around releasing. In this case I will be able to provide updates faster and better. I will make much more tests in the future so merging PRs will be safe for the project.

Hopefully it will work good and we will iterate actively on new features/fixes with this setup 🤘

**Comment by cojoclaudiu** [comment]
I'm wainting to check the V3 and see what are the breaking changes.

useTransformEffect, MiniMap, KeepScale made me courios.

I was checking now the docs for KeepScale but to be honest I don't see much here https://prc5.github.io/react-zoom-pan-pinch/?path=/docs/examples-keep-scale--keep-scale

**Comment by prc5** [comment]
> I'm wainting to check the V3 and see what are the breaking changes.
> 
> useTransformEffect, MiniMap, KeepScale made me courios.
> 
> I was checking now the docs for KeepScale but to be honest I don't see much here https://prc5.github.io/react-zoom-pan-pinch/?path=/docs/examples-keep-scale--keep-scale

Breaking changes are mostly around render props and rerendering in general - I made the hooks to allow developers to choose on how they want to rerender their components, this is related to tons of the performance issues which were happening because of bad design for interacting with context and data in the zoom pan pinch.

I hope it will close the performance topic once for good and I will be able to solve bugs and add some more features 👍🏻

**Pull request merged**
