### PR TITLE
Fix zoom callback + various versioning bumps

### PR DESCRIPTION
**Pull request by dlcognite**
fixes https://github.com/prc5/react-zoom-pan-pinch/issues/11 fully

### CODE REVIEW

**Comment by mominafiz** [comment]
Looking forward to this PR to merge. I have one such use case where I need to know the current scale after zoom In and zoom out. Maintainer, could you please review this?

**Comment by prc5** [comment]
Hey, I would love to do it but the build and tests are not passing so it is impossible to merge, fix it please :)Temat: Re: [prc5/react-zoom-pan-pinch] Fix zoom callback + various versioning bumps (#52)Data: 2019-12-13 2:10Nadawca: "mominafiz" Adresat: "prc5/react-zoom-pan-pinch" ; DW: "Maciej Pyrc" ; "Review requested" ; Looking forward to this PR to merge. I have one such use case where I need to know the current scale after zoom In and zoom out. Maintainer, could you please review this?

**Comment by dlcognite** [comment]
Will fix that up today!

**Comment by dlcognite** [comment]
fixed :)

**Comment by prc5** [comment]
@all-contributors please add dlcognite for code

**Pull request merged**
